name: Hardhat Local Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  hardhat-test:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max_old_space_size=4096

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22 (latest LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          cache: npm
      - run: node -v

      - name: Install deps
        run: npm ci

      - name: Compile
        run: npx hardhat compile

      - name: Start local Hardhat node
        run: |
          npx hardhat node &
          # attend que le port 8545 réponde
          for i in {1..20}; do
            if nc -z localhost 8545; then
              echo "Hardhat node is up"; break
            fi
            echo "Waiting for Hardhat node..."
            sleep 1
          done

      - name: Run tests on localhost
        run: npx hardhat test --network localhost
